name: flutter_ticker_sample
description: A sample app demonstrating the Flutter Ticker library.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Local dependency to the Flutter Ticker library
  flutter_ticker:
    path: ../flutter_ticker_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
