name: ticker
description: A Flutter widget for smooth, animated text transitions with scrolling effects, similar to financial tickers or departure boards.
version: 0.1.3
homepage: https://github.com/codevalley/flutter_ticker
repository: https://github.com/codevalley/flutter_ticker
issue_tracker: https://github.com/codevalley/flutter_ticker/issues

# Author information is included in the LICENSE file
# License is required for pub.dev
license: Apache-2.0
# Add topics for better discoverability
topics:
  - animation
  - text
  - ticker
  - ui

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This package doesn't include any assets or fonts
